### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by ItsCEED** [NiGHT757/MapRestriction#1]
Im sure this is very early...

1. Dont count bots
2. Make sure to update on player connect/discount as well instead of round start only (deathmatch)
3. Maybe, JUST MAYBE use the deathamtch api to limit the spans within the allowed area?

**Comment by NiGHT757** [comment]
1. Added
2. Added
3. I don't know what deatmatch api you mean, please provide more info.

[v0.0.2](https://github.com/NiGHT757/MapRestriction/releases/tag/v0.0.2)

I didn't test this version, if there are any problems please comment here :)
Also update the map config again because of [this](https://github.com/NiGHT757/MapRestriction/commit/aa6943c313d5fec74e226140509ed2b867fa402c)
